// @generated by scripts/generate-database-contract.py; do not edit.

pub const DATABASE_CONTRACT_FORMAT: &str = "ldgr.database-contract.v1";
pub const ADAPTER_DATABASE_CONTRACT_FORMAT: &str = "ldgr.adapter-database-contract.v1";
pub const DATABASE_CONTRACT_HASH: &str =
    "sha256:b7677218bb9fb3fe39ef63d25b89fcf3fe7fe6d94cc6bbef22dbc448e0e9fb92";
pub const DATABASE_RELEASE_SET_HASH: &str =
    "sha256:bce8cec3135d79fb73bc64336c17129bd8253b24fc4f7520adeda325b425ed9f";
pub const GENERATED_CORE_SCHEMA_VERSION: i64 = 5;
pub const GENERATED_DATABASE_CONTRACT_JSON: &str = include_str!("../schema/database-contract.json");
pub const GENERATED_DATABASE_RELEASE_SET_JSON: &str =
    include_str!("../schema/database-release-set.json");
pub const GENERATED_CORE_COMPATIBILITY_JSON: &str =
    include_str!("../schema/core-compatibility.json");

pub const GENERATED_DATABASE_COMPONENTS: &[DatabaseComponentContract] =
    &[DatabaseComponentContract {
        namespace: "core",
        schema_version: 5,
        minimum_core_schema: 5,
        migration_digest: "sha256:b8230dce6e78b58c75dbe0f69cf771276f513be4e72a8291c2a4965f5b777a35",
    }];
