// @generated by scripts/generate-database-contract.py; do not edit.

pub const DATABASE_CONTRACT_FORMAT: &str = "ldgr.database-contract.v1";
pub const ADAPTER_DATABASE_CONTRACT_FORMAT: &str = "ldgr.adapter-database-contract.v1";
pub const DATABASE_CONTRACT_HASH: &str = "sha256:6f5d93af0d6b46ca9f2c6327e694a90c84d3f2d5906e0bd69424d3d4b0ea2a98";
pub const GENERATED_CORE_SCHEMA_VERSION: i64 = 4;
pub const GENERATED_DATABASE_CONTRACT_JSON: &str = include_str!("../schema/database-contract.json");

pub const GENERATED_DATABASE_COMPONENTS: &[DatabaseComponentContract] = &[
    DatabaseComponentContract { namespace: "bench", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "code", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "conduct", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "core", schema_version: 4, minimum_core_schema: 4, migration_digest: "sha256:661648944372068c03db6bbe67c77e1b1ec0b9f224014c800ed1f2558718f88e" },
    DatabaseComponentContract { namespace: "evidence", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:32131552be533042c2a8118a7260132f98a6f0c6245e40e863f5c0ee6682dd26" },
    DatabaseComponentContract { namespace: "example", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "explore", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "private-commercial", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "programbench", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "recall", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    DatabaseComponentContract { namespace: "research", schema_version: 4, minimum_core_schema: 4, migration_digest: "sha256:7d4a8ff306fc459d9671dd3251056933d42653f2fe1558ae4d35447f8b289848" },
    DatabaseComponentContract { namespace: "security", schema_version: 1, minimum_core_schema: 4, migration_digest: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
];
